progressive/step3/example-app/README.md, progressive/step4/egg-ua/app/extend/context.js, progressive/step4/egg-ua/package.json, progressive/step4/egg-ua/test/fixtures/test-app/app/router.js, progressive/step4/egg-ua/test/fixtures/test-app/package.json, progressive/step4/egg-ua/test/ua.test.js, progressive/step4/example-app/README.md, progressive/step4/example-app/package.json, progressive/step4/example-framework/README.md, progressive/step4/example-framework/package.json
=> fix: use file link && cp ua

cnode-api/config/config.default.js, cnode-api/test/app/controller/topics.test.js, cnode-api/test/app/service/topics.test.js
Add service mock and HTTP client mock in `cnode-api/test` to avoid `Timeout`.
=> fix: add mock in cnode api unittest

download/app/controller/index.js
https://github.com/eggjs/examples/pull/28#discussion_r119522042
=> fix: use stream at download example

sequelize-example/app/model/post.js, sequelize-example/app/model/user.js, sequelize-example/package.json
升级 egg-sequelize dependecy 到3.x
=> deps: update to use egg-sequelize 3.x

hackernews-async-ts/app/controller/index.d.ts, hackernews-async-ts/app/controller/news.ts, hackernews-async-ts/app/service/HackerNews.ts, hackernews-async-ts/app/service/index.d.ts, hackernews-async-ts/config/config.ts, hackernews-async-ts/config/defaultConfig.ts, hackernews-async-ts/package.json, hackernews-async-ts/test/app/service/HackerNews.test.ts, hackernews-async-ts/tslint.json
主要优化点
- 去掉 @types/egg @types/egg-mock 依赖
- service 和 controller 定义统一到一个文件中
- config 类型定义优化
=> feat: typescript deme remove @types/egg dependency

sequelize-example/migrations/20170601073501-init-migration.js
see https://github.com/eggjs/egg-sequelize/pull/24#
=> refact: use co.wrap to write migration

hackernews-async-ts/package.json
close https://github.com/eggjs/egg/issues/1386
=> docs: fix ts npm scripts

hackernews/README.md, hackernews/app/router.js, hackernews/package.json, hackernews/test/app/controller/news.test.js, hackernews/test/app/service/HackerNews.test.js
- 书写风格升级到Egg2.x
- 修改了一下readme
- 更新了一些依赖
=> style(hackernews):upgrade to egg2.x

cnode-api/app/controller/topics.js
=> 加上 type, 不然报错

.github/PULL_REQUEST_TEMPLATE.md, hackernews-async-ts/.autod.conf.js, hackernews-async-ts/package.json, hackernews-async-ts/test/app/controller/news.test.ts, hackernews-async-ts/test/app/service/HackerNews.test.ts
- upgrade to egg2
- fix ci cause by https://github.com/eggjs/egg-mock/pull/62
=> feat: upgrade ts to egg2

httpclient/app/controller/httpclient.js, httpclient/app/router.js, httpclient/package.json
fix error: httpclient can`t start.
=> fix(httpclient): router delete -> del

hackernews-async-ts/package.json
=> fix(lint): hackernews-async-ts should use tslint

assets-with-roadhog/config/config.default.js, assets-with-roadhog/config/config.prod.js
=> fix(assets-with-roadhog): unknown ip

assets-with-umi/app/assets/.umirc.js
=> fix(umi): disable service worker

hackernews-async-ts/package.json, hackernews-async-ts/test/app/service/News.test.ts
=> fix: ts test && pkg scripts

.gitignore, view-nunjucks/package.json, view-nunjucks/test/index.test.js, view-nunjucks/uitest/helper.js, view-nunjucks/uitest/homepage.test.js, view-nunjucks/uitest/mocha.opts
=> feat: support macaca ui test

sequelize-example/app/controller/post.js
=> fix: Update post.js

.travis.yml, multipart/.gitignore, multipart/app/controller/ajax.js, multipart/app/controller/buffer.js, multipart/app/controller/form.js, multipart/app/controller/multiple.js, multipart/package.json
=> refactor: use pump instead of stream modules

passport/config/config.default.js
=> fix: missing keys

sofa-rpc/package.json, sofa-rpc/test/app/controller/home.test.js, sofa-rpc/test/server.test.js
=> test: fix sofa-rpc ci

multipart-file-mode/app/controller/ajax.js, multipart-file-mode/app/controller/form.js, multipart-file-mode/app/controller/multiple.js
=> fix: should alway remove tmp files on try finally

hackernews-datahub/README.md, hackernews-datahub/config/config.default.js, hackernews-datahub/config/plugin.js, hackernews-datahub/macaca-datahub.config.js, hackernews-datahub/package.json, hackernews-datahub/test/e2e/datahub.test.js
- [ x] tests and/or benchmarks are included
- [ x] documentation is changed or added
- [ x] commit message follows commit guidelines
remove `egg-datahub` from `hackernews-datahub`
=> fix: hackernews-datahub remove egg-datahub

sequelize/README.zh-CN.md
=> docs: typo Update README.zh-CN.md

README.md
=> docs: typo Update README.md

.gitignore, sofa-rpc/config/config.default.js, sofa-rpc/config/plugin.js, sofa-rpc/package.json
=> fix: sofa rpc example ci

bodyParser/REAME.md, bodyParser/app/controller/home.js, bodyParser/app/router.js, bodyParser/config/config.default.js, bodyParser/package.json, bodyParser/test/home.test.js
=> feat: add body-parser example

passport/README.md, passport/app/controller/home.js, passport/app/router.js, passport/config/config.default.js, passport/config/plugin.js, passport/package.json
passport plugin pull request: https://github.com/eggjs-community/egg-passport-yuque/pull/1
=> feat: add egg-passport-yuque example

httpclient/app/controller/httpclient.js, httpclient/app/router.js
https://github.com/node-modules/urllib/pull/322
=> feat: httpclient upload files example

sequelize-ts/package.json, sequelize/app/service/post.js, sequelize/app/service/user.js, sequelize/package.json, sequelize/test/app/service/post.test.js
Upgrade `egg-sequelize` and `sequelize-cli` to latest version(5.x)
=> feat: upgrade sequelize version

todomvc/app.js, todomvc/appveyor.yml, todomvc/config/config.unittest.js, todomvc/config/database/init.js, todomvc/package.json, todomvc/test/app/controller/home.test.js
=> fix: auto sync db on local env

multipart-file-mode/app/controller/ajax.js, multipart-file-mode/app/controller/form.js, multipart-file-mode/app/controller/home.js, multipart-file-mode/app/controller/multiple.js, multipart-file-mode/app/router.js, multipart-file-mode/config/config.default.js, multipart-file-mode/config/plugin.js, multipart-file-mode/package.json, multipart-file-mode/test/index.test.js, multipart/app/controller/ajax.js, multipart/app/controller/buffer.js, multipart/app/controller/form.js, multipart/app/controller/home.js, multipart/app/controller/multiple.js, multipart/app/router.js, multipart/config/config.default.js, multipart/config/plugin.js, multipart/package.json, multipart/test/index.test.js
=> feat: multipart upgrade to egg v3
